### ISSUE TITLE
Link to "PHP Shortcode Snippets" made by DinodDabs is dead

### ISSUE THREAD

**Issue by 8712staefa** [bludit/plugins-repository#245]
the link to "PHP Shortcode Snippets" made by DinodDabs is dead (https://aestheticode.gumroad.com/l/bludit-php-shortcodes).
Any idea where one can get that plugin?

**Comment by clickwork-git** [comment]
Have you already contacted the author:

http://aestheticode.net

**Comment by Zebraslive** [comment]
I updated the payment link a while ago so you can close this issue now @clickwork-git

https://plugins.bludit.com/plugin/php-shortcodes @8712staefa

**Comment by 8712staefa** [comment]
Thanks
